### PR TITLE
[DR-1258] Fix bug with translations in billing currency

### PR DESCRIPTION
**Pull request by mvillaseco**
# Overview
 Add translations to currency.

# Changes
 - Modify billing view.

### CODE REVIEW

**Comment by andresmoschini** [comment]
👍

**Comment by mvillaseco** [comment]
English:



Spanish:

**Comment by nreal** [comment]
On this ticket also https://www.screencast.com/t/SdvHKBWQ2 exists this problem, do you fix in other PR?

**Comment by mvillaseco** [comment]
Yeah, i'll add it here also and update the Jira ticket.

**Comment by nreal** [comment]
👍

**Comment by mvillaseco** [comment]
English:


Spanish:

**Comment by andresmoschini** [comment]
Great! thanks @mvillaseco, good catch @nreal!

**Pull request merged**
