### PR TITLE
fix: add security headers

### PR DESCRIPTION
**Pull request by cbernat**
Add missing securiti headers, according to the security report. [Jira link](https://makingsense.atlassian.net/browse/DW-771)

### CODE REVIEW

**Comment by cbernat** [comment]
@VicThorX @swidzinskiMS is it ok to merge this? Could you please review?

**Comment by andresmoschini** [comment]
👍

**Review by swidzinskiMS — COMMENTED** [review]
Seems alright 👍

**Comment by VicThorX** [comment]
👍

**Pull request merged**
