### PR TITLE
Dr-1498 Add login admin page

### PR DESCRIPTION
**Pull request by mvillaseco**
# Overview
 Add Login Admin Page 

# Changes
 - Add new page
 - Add new content

# In progress
 - Final endpoint
 - Tests

### CODE REVIEW

**Comment by andresmoschini** [comment]
👍  We could start sharing it with @Juampi1790  to get some feedback

**Comment by mvillaseco** [comment]
User not allowed to impersonate:


Client not exist:

**Comment by andresmoschini** [comment]
👍

**Comment by alegarciamina** [comment]
Looks great!

Just one comment, what do you think about adding another error to let the user know when client is inactive?
We could check `pending_activation` flag so we avoid the unexpected error.

**Pull request merged**
