### PR TITLE
DR-1035 - Configuration Page - Add icons status dkim and spf

### PR DESCRIPTION
**Pull request by nreal**
Hi team,
I added icons of dKim and Spf status as in domains list page

Could you review?
Example:

### CODE REVIEW

**Comment by andresmoschini** [comment]
Nice! 

If you want, you can also create tests for the different icons. But when you change how the data is obtained you have to update those tests.

Could you work along @mvillaseco to fix vertical alignment and spacing?

**Comment by nreal** [comment]
Ok, Yes it is possible. I will add those tests.

**Comment by andresmoschini** [comment]
:+1:

**Comment by mvillaseco** [comment]
💯 

Nice PR!

**Comment by martinkeimel** [comment]
Looks great! 🔥

**Pull request merged**
