### PR TITLE
[DR-1245] - Add separators for numbers in my plan section

### PR DESCRIPTION
**Pull request by nreal**
Hi team,
I add separator to numbers in my plan section

Example:

Could you review?

### CODE REVIEW

**Comment by andresmoschini** [comment]
Great @nreal!, I have a little doubt, does it work in the same way in English and Spanish? did you validate that this behavior is the right one?

**Comment by nreal** [comment]
Yes, have the same behaviour in the two languages, I'll add the tests to this question

**Comment by andresmoschini** [comment]
> Yes, have the same behaviour in the two languages, I'll add the tests to this question

I mean, did you validate with Juan Pablo if that behavior is fine?

**Comment by nreal** [comment]
No, I'll validate with Juan Pablo about this feature

**Comment by nreal** [comment]
In English, MY CONSUMPTION, AMOUNT OF EMAILS and EMAILS SENT OUT OF PLAN the separator is with `,`
In Spanish, the number separator is with `.`

**Comment by nreal** [comment]
I'll Proceed to close this PR because the scope is changed

**Pull request closed without merging**
